[package]
name = "gpu_math"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
pollster = "0.4.0"
rand = "0.9.0"
wgpu = "24.0.3"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benches"
harness = false
